"""remnawave_panels_add_node_secret_and_port

Revision ID: b3df7424ed24
Revises: 840e4016bb31
Create Date: 2026-06-30 23:04:57.053530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3df7424ed24'
down_revision: Union[str, Sequence[str], None] = '840e4016bb31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remnawave_panels', sa.Column('node_secret_key', sa.String(length=512), nullable=False))
    op.add_column('remnawave_panels', sa.Column('node_port', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remnawave_panels', 'node_port')
    op.drop_column('remnawave_panels', 'node_secret_key')
    # ### end Alembic commands ###
