"""remnawave_panels_add_api_token_rename_name_to_tag

Revision ID: d7b0ce2024b9
Revises: eacfb67e2a92
Create Date: 2026-06-30 02:40:50.943010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b0ce2024b9'
down_revision: Union[str, Sequence[str], None] = 'eacfb67e2a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remnawave_panels', sa.Column('tag', sa.String(length=255), nullable=False))
    op.add_column('remnawave_panels', sa.Column('api_token', sa.String(length=512), nullable=False))
    op.drop_column('remnawave_panels', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remnawave_panels', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('remnawave_panels', 'api_token')
    op.drop_column('remnawave_panels', 'tag')
    # ### end Alembic commands ###
