"""remnawave_panel_node_secret_key_text

Revision ID: fcdb392fa44e
Revises: b3df7424ed24
Create Date: 2026-07-01 01:29:56.498351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcdb392fa44e'
down_revision: Union[str, Sequence[str], None] = 'b3df7424ed24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('remnawave_panels', 'node_secret_key',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('remnawave_panels', 'node_secret_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###
